services:
  app:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./src/public:/app
      - dist:/app/dist/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  node:
    image: 'learning/typescript3.9.10:local'
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./src:/usr/src
      - dist:/usr/src/public/dist/
      - node_modules:/usr/src/node_modules/
    ports:
      - '3000:3000'

volumes:
  node_modules:
    driver: local

  dist:
    driver: local
